name: run_pydsd_ci.yml
on: [push,pull_request ]
jobs:
  build_and_publish:
    name: Setup Environment, and run test suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: 3.7
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pydsdci
          environment-file: pydsd-ci.yml
      - name: Run Pytest
        shell: bash -l {0}
        run: |
          pytest
      - name: Build package
        shell: bash -l {0}
        run: |
          python -m build --wheel --outdir dist/ .
      - name: Publish package to PYPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/master'
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: ${{ secrets.PYPI_USERNAME }}
          password: ${{secrets.PYPI_PASSWORD}}
          #repository_url: https://test.pypi.org/legacy/
      - name: Build Documentation
        shell: bash -l {0}
        run: |
          pwd
          pip install -e .
          cd docs
          make clean
          make html
      - name: Upload Documentation
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags') && github.ref == 'refs/heads/master'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
